### ISSUE TITLE
Ktor + ArrowKT 

### ISSUE THREAD

**Issue by Mando75** [mjovanc/awesome-ktor#2]
One of the maintainers of [ArrowKT](https://arrow-kt.io/) has a pretty comprehensive demo repo for integrating ArrowKT with Ktor. Might be beneficial to add to this list as an educational project. 

https://github.com/nomisRev/ktor-arrow-example 

Uses ArrowKT, SQLDelight, Kotest, Test Containers

**Comment by mjovanc** [comment]
Thanks a lot for the suggestion! I've added it to the list.
