### ISSUE TITLE
Couple additions

### ISSUE THREAD

**Issue by nomisRev** [mjovanc/awesome-ktor#3]
# Projects
- [Cohort is a Spring Actuator style replacement for Ktor.](https://github.com/sksamuel/cohort)
- [SuspendApp Ktor - functional resource/lifecycle management](https://github.com/arrow-kt/suspendapp#suspendapp-with-ktor)

### Don't have Ktor specific integration, but all are designed to be used with Ktor
- [Kotlin-Kafka (has Ktor Plugin on roadmap)](https://github.com/nomisRev/kotlin-kafka)
- [Hoplite: typesafe loading configuration files](https://github.com/sksamuel/hoplite)
- [Tribune - parse don't validate](https://github.com/sksamuel/tribune)

# Educational projects
- [Ktor mircoservice with Kafka, Arrow, SqlDelight, Kotest, etc](https://github.com/47deg/gh-alerts-subscriptions-kotlin)
- [Ktor zero-downtime deployment on K8s](https://github.com/nomisRev/ktor-k8s-zero-downtime)

# Videos
- [Building (Ktor) applications with Kotlin and Arrow.kt in style](https://www.youtube.com/watch?v=g79A6HmbW5M)
- [Graceful Resource Handling Using Structured Concurrency in Kotlin](https://www.youtube.com/watch?v=zKrTBH8jqH4)

**Comment by mjovanc** [comment]
Great additions! Thanks a lot for taking the time. Added.
